### ISSUE TITLE
I try with "node insertDemoData.js" but i have error!

### ISSUE THREAD

**Issue by VennDev** [Kuzma02/Electronics-eCommerce-Shop-With-Admin-Dashboard-NextJS-NodeJS#12]
![image](https://github.com/user-attachments/assets/e6409af6-4089-44ab-aa07-e4306f26e819)

Error:
![image](https://github.com/user-attachments/assets/a3fb9c9e-2f04-4b0e-b04a-a19dd5008977)

**Comment by Kuzma02** [comment]
@VennDev Hi! I don't have access to your code, but I can give you some steps you can try:
1. Verify the .env File Location:
Double-check that both of your .env files are located in the right places, as Prisma will look for it. Also, check whether both .env files have the same DATABASE_URL variable.
2. Check your npm packages, particularly the dotenv package
Check whether you have installed all npm packages with "npm install" and that you have the dotenv package installed. If you already have installed it, try the following. Put at the top of insertDemoData.js the following line: require('dotenv').config();
3. Check your database
Ensure that you have MySQL database installed on your PC and that it is running on the port that you defined in both .env files. Also, check whether you already have data in your Shop database because you can't insert new data in the database if you already have data there.

I hope it will help you to solve the problem.

**Comment by VennDev** [comment]
Thanks for you!
